# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commment',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='commment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
